apiVersion: v1
kind: Pod 
metadata:
  name: init-container-pod
  labels:
    app: init-container-demo
    type: init-container
    object: init-container
spec:
  initContainers:
    - name: init-container-alpine-init
      image: alpine:3.14
      command:
        - wget
        - "-O"
        - /var/tmp/index.html
        - https://github.com/sudheerduba/initContainer_demo/blob/main/index.html?raw=true
      volumeMounts:
        - name: shared-data
          mountPath: /var/tmp
  containers:
    - name: main-container
      image: nginx:1.22.0
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-data
      emptyDir: {}