apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container
    type: webserver
spec:
  containers:
    - name: container-write
      image: alpine:3.14
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/tmp/index.html; sleep 10; done"]
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /var/tmp
    - name: container-serve
      image: nginx:1.22.0
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
volumes:
    - name: shared-data
      emptyDir: {}
        