apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-demo-rc
  labels:
    app: nginx
    type: rc-prod
spec:
  replicas: 3
  selector:
    app: nginx
    env: prod
  template:
    metadata:
      name: nginx-demo-pod
      labels:
        app: nginx
        env: prod