apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-demo-rc
  labels:
    app: nginx
    type: rc-prod
spec:
  replicas: 3
  selector:
    app: nginx
    env: prod
  template:
    metadata:
      name: nginx-demo-pod
      labels:
        app: nginx
        env: prod
        release: v1.0
    spec:
      containers:
        - name: write-container
          image: alpine:3.14
          command: ["/bin/sh"]
          args: ["-c", "while true; do date >> /var/log/index.html; sleep 10; done"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-data
              mountPath: /var/log
        - name: serving-container
          image: nginx:1.22.0
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
            - name: nginx-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-data
          emptyDir: {}