apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-demo-daemonset
  labels:
    app: nginx
    type: daemonset-prod
    env: prod
spec:
  selector:
    matchLabels:
      app: nginx
      env: prod
      release: v1.0
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
      - key: env
        operator: In
        values:
          - prod
      - key: release
        operator: In
        values:
          - v1.0
          - v1.1
  template:
    metadata:
      name: nginx-demo-pod
      labels:
        app: nginx
        env: prod
        release: v1.0
    spec:
      containers:
        - name: write-container
          image: alpine:3.14
          command: ["/bin/sh"]
          args: ["-c", "while true; do date >> /var/log/index.html; sleep 10; done"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /var/log
        - name: serving-container
          image: nginx:1.22.0
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: shared-data
          emptyDir: {}